// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYuox36DO3vV9jG3lz_plWMACLEjNSreo',
    appId: '1:125785357523:web:7e1582e24f34b190b76826',
    messagingSenderId: '125785357523',
    projectId: 'todoapplist-5c955',
    authDomain: 'todoapplist-5c955.firebaseapp.com',
    storageBucket: 'todoapplist-5c955.firebasestorage.app',
    measurementId: 'G-KNRNSRXLWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGcoZQL9bkr__kKLG9m8jdMpolv-AlOFY',
    appId: '1:125785357523:android:ffdfa94dcdd224b4b76826',
    messagingSenderId: '125785357523',
    projectId: 'todoapplist-5c955',
    storageBucket: 'todoapplist-5c955.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuyCXJeLicMEjUX8o4xWKspLkfKgQEeEc',
    appId: '1:125785357523:ios:4eab7e63f00fbab5b76826',
    messagingSenderId: '125785357523',
    projectId: 'todoapplist-5c955',
    storageBucket: 'todoapplist-5c955.firebasestorage.app',
    iosBundleId: 'com.saulmestanza.todo',
  );
}
